# Generated by Django 4.2.3 on 2023-07-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
