# Generated by Django 4.2.3 on 2023-07-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='requested_url',
            field=models.CharField(max_length=20),
        ),
    ]
