# Generated by Django 4.2.3 on 2023-07-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_campaign_requested_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='emails',
            field=models.CharField(default=12, max_length=10000),
            preserve_default=False,
        ),
    ]
