# Generated by Django 4.2.3 on 2023-07-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='emails',
        ),
        migrations.AddField(
            model_name='campaign',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
