# Generated by Django 4.2.3 on 2023-07-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_remove_campaign_email_campaign_found_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='found_email',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='requested_url',
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(default='test description', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='title',
            field=models.CharField(default='Test Title', max_length=100),
            preserve_default=False,
        ),
    ]
