# Generated by Django 4.2.3 on 2023-07-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_alter_campaign_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.TextField(max_length=254),
        ),
    ]
